name: car_payments
channels:
  - defaults
  - conda-forge
dependencies:
<<<<<<< HEAD
  - python=3.10
=======
  - python=3.11
>>>>>>> 75ed1aee9a960782c7edb80f147d90878fe12d60
  - pip
  - pip:
      - -r requirements.txt
